package org.linketinder.repository

import groovy.sql.Sql
import java.sql.SQLException

class DataBaseDAO {
    private static final String URL = "jdbc:postgresql://localhost/Linketinder"
    private static final String USER = 'postgres'
    private static final String PASSWORD = 'j6032'
    private static final String DRIVER = 'org.postgresql.Driver'

    private Sql sql

    DataBaseDAO() {
        try {
            this.sql = Sql.newInstance(URL, USER, PASSWORD, DRIVER)
        } catch (SQLException e) {
            println("Erro ao conectar ao banco de dados: ${e.message}")
            e.printStackTrace()
        }
    }

    void execute(String query) {
        try {
            sql.execute(query)
        } catch (SQLException e) {
            println("Erro ao executar query: ${e.message}")
            e.printStackTrace()
        }
    }

    void close() {
        if (sql != null) {
            sql.close()
        }
    }

    static void main(String[] args) {
        DataBaseDAO database = new DataBaseDAO()

        database.execute '''
          CREATE TABLE Outra (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
            firstname   VARCHAR(64),
            lastname    VARCHAR(64)
          );
        '''

        database.close()
    }
}
